import ForgotPassword from "@/components/auth/ForgottenPassword";
import React from "react";

export const metadata = {
  title: "Forgot Password | Glass File",
  description: "Generated by Glass File Website",
};

const page = () => {
  return (
    <div>
      <ForgotPassword />
    </div>
  );
};

export default page;
