import TermsOfService from "@/components/terms/Terms";
import Terms from "@/components/terms/Terms";
import React from "react";

export const metadata = {
  title: "ToS | Glass File",
  description: "Generated by Glass File Web App",
}

const page = () => {
  return (
    <div>
      <TermsOfService />
    </div>
  );
};

export default page;
