import JurorProtocolOverview from '@/components/footerLinks/JurorProtocolOverview'
import React from 'react'

export const metadata = {
  title: "Juror Protocol | Glass File",
  description: "Generated by Glass File  Web App",
}
const JurorProtocol = () => {
  return (
    <div>
        <JurorProtocolOverview />
    </div>
  )
}

export default JurorProtocol