import OTPVerify from "@/components/auth/OTPVerify";
import React, { Suspense } from "react";

export const metadata = {
  title: "OTP Verify | Glass File",
  description: "Generated by Glass File Website",
};

const OTPVerifyPage = () => {
  return (
    <div>
      <Suspense fallback={<div className="flex justify-center items-center h-screen">Loading...</div>}>
        <OTPVerify />
      </Suspense>
    </div>
  );
};

export default OTPVerifyPage;
