import ContactForm from "@/components/contactUs/ContactUs";
import React from "react";

export const metadata = {
  title: "Contact Us | Glass File",
  description: "Generated by Glass File Web App",
}

const page = () => {
  return (
    <div>
      <ContactForm />
    </div>
  );
};

export default page;
