import ResetPasswordCom from "@/components/auth/ResetPassword";
import { Suspense } from "react";

export const metadata = {
  title: "Reset Password | Glass File",
  description: "Generated by Glass File Website",
};

const page = () => {
  return (
    <Suspense fallback={<div>Loading...</div>}>
    <ResetPasswordCom />
  </Suspense>
  );
};

export default page;
