import UserCreate from "@/components/userCreate/UserCreate";
import React from "react";

export const metadata = {
  title: "Sign Up | Glass File",
  description: "Generated by Glass File Website",
};

const page = () => {
  return (
    <div>
      <UserCreate />
    </div>
  );
};

export default page;
