import FAQCom from '@/components/faqCom/FAQCom'
import React from 'react'

export const metadata = {
  title: "FAQ | Glass File",
  description: "Generated by Glass File Web App",
};

const FAQComponents = () => {
  return (
    <div>
      <FAQCom />
    </div>
  )
}

export default FAQComponents
