import JurorPipelineOverview from '@/components/footerLinks/JurorPipelineOverview'
import React from 'react'

export const metadata = {
  title: "Juror Pipeline | Glass File",
  description: "Generated by Glass File  Web App",
}

const JurorPipeline = () => {
  return (
    <div><JurorPipelineOverview /></div>
  )
}

export default JurorPipeline