import FeePolicyOverview from '@/components/footerLinks/FeePolicy'
import React from 'react'

export const metadata = {
  title: "Fee Policy | Glass File",
  description: "Generated by Glass File  Web App",
}

const FeePolicy = () => {
  return (
    <div>
      <FeePolicyOverview />
    </div>
  )
}

export default FeePolicy