
import PrivacyPolicy from "@/components/footerLinks/PrivacyPolicy";
import React from "react";

export const metadata = {
  title: "Privacy Policy | Glass File",
  description: "Generated by Glass File Web App",
}

const page = () => {
  return (
    <div>
      <PrivacyPolicy />
    </div>
  );
};

export default page;
