import GovernanceAndAccountabilityOverview from '@/components/footerLinks/GovernanceAndAccountability'
import React from 'react'

export const metadata = {
  title: "Platform Governance & Accountability | Glass File",
  description: "Generated by Glass File  Web App",
}
const GovernanceAndAccountability = () => {
  return (
    <div>
      <GovernanceAndAccountabilityOverview />
    </div>
  )
}

export default GovernanceAndAccountability