import DashboardContainer from '@/components/dashboard/page'
import React from 'react'

export const metadata = {
  title: "Dashboard | Glass File",
  description: "Generated by Glass File Web App",
}

const UserDashboard = () => {
  return (
    <div><DashboardContainer/></div>
  )
}

export default UserDashboard