import GovernanceCharterOverview from '@/components/footerLinks/GovernanceCharterOverView'
import React from 'react'

export const metadata = {
  title: "Platform Governance Charter | Glass File",
  description: "Generated by Glass File  Web App",
}
const GovernanceCharter = () => {
  return (
    <div>
        <GovernanceCharterOverview />
    </div>
  )
}

export default GovernanceCharter
