import LoginUser from "@/components/login/Login";
import React from "react";

export const metadata = {
  title: "Login | Glass File",
  description: "Generated by Glass File Website",
};

const page = () => {
  return (
    <div>
      <LoginUser />
    </div>
  );
};

export default page;
