import React from 'react'
import JurorRecusalForm from '../../(form)/juror-recusal/page'

// export const metadata = {
//   title: "Juror Ethics & Responsibilities | Glass File",
//   description: "Generated by Glass File Web App",
// }

const JurorEthics = () => {
  return (
    <div><JurorRecusalForm /></div>
  )
}

export default JurorEthics
