import JurorEthicsOverview from '@/components/footerLinks/JurorEthicsOverview'
import React from 'react'


export const metadata = {
  title: "Juror Ethics & Responsibilities | Glass File",
  description: "Generated by Glass File  Web App",
}
const JurorEthics = () => {
  return (
    <div><JurorEthicsOverview /></div>
  )
}

export default JurorEthics