import LegalResourcesOverView from '@/components/footerLinks/LegalResourcesOverView'
import React from 'react'

export const metadata = {
  title: "Legal Resources | Glass File",
  description: "Generated by Glass File  Web App",
}

const LegalResources = () => {
  return (
    <div>
        <LegalResourcesOverView />
    </div>
  )
}

export default LegalResources